spring.application.name= user-service

spring.datasource.url= jdbc:postgresql://localhost:5432/shopsphere_product
spring.datasource.username= postgres
spring.datasource.password= 0000

spring.jpa.hibernate.ddl-auto= update
spring.jpa.properties.hibernate.show-sql= true

server.port= 8082